version: '3.8'

services:
  app:
    build: .
    container_name: random-image-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SAUCENAO_API_KEY=${SAUCENAO_API_KEY:-APIKEYHERE}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminpass}
    command: gunicorn --bind 0.0.0.0:5000 app:app

volumes:
  data:
    driver: local
